name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_TIME_API }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: "True"
          SHOW_LINES_OF_CODE: "True"
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: all_time
          SHOW_TIME: "True"
          SHOW_MASKED_TIME: "True"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"

